version: "3.8"

services:
  captcha-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_MAX_IDLE=10
      - REDIS_MAX_RETRIES=3
      - UNDER_MAINTENANCE=false
      - HTTP_SERVER_TIMEOUT=10
      - HTTP_PORT=8080
      - JWT_KEY=your-jwt-secret-key

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: